apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-deployment
  labels:
    app: alpine
spec:
  replicas: 3 # Você pode ajustar o número de réplicas desejado
  selector:
    matchLabels:
      app: alpine
  template:
    metadata:
      labels:
        app: alpine
    spec:
      containers:
      - name: alpine
        image: alpine:latest # Use alpine:latest ou uma versão específica como alpine:3.19
        command: ["sleep", "3600"] # Exemplo: Mantém o container rodando por 1 hora
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"
          requests:
            memory: "32Mi"
            cpu: "50m"