# Usa a imagem oficial do Nginx baseada em Alpine
FROM nginx:alpine

# Exemplo:
COPY ./html /usr/share/nginx/html

# Expõe a porta 80, que é a porta padrão para HTTP
EXPOSE 80


CMD ["nginx", "-g", "daemon off;"]