apiVersion: v1
kind: Service
metadata:
  name: private-registry-service
  labels:
    app: private-registry
spec:
  selector:
    app: private-registry
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP # Ou NodePort, LoadBalancer